#!/usr/bin/python
import sys

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    CYAN = '\033[36m'
    RESET_ALL = '\033[0m'
    MAGENTA = '\033[35m'
    
print(bcolors.CYAN+u"\u25B6"+ bcolors.MAGENTA+" Directory Indices")
print(bcolors.OKBLUE+"#")
for line in sys.stdin:
	temp = line.replace('\n','').split('\t')
	print(bcolors.OKBLUE+"#    "+bcolors.WARNING+"["+bcolors.FAIL+temp[0]+bcolors.WARNING+"]"+bcolors.HEADER+"   =>   "+bcolors.OKGREEN+temp[1])
print(bcolors.OKBLUE+"#")